### ISSUE TITLE
Failed Prop Type warning generated from Drawit

### ISSUE THREAD

**Issue by aw-yt** [emumba-com/drawit#13]
When using Drawit as a library in my project, i can see a warning for Failed prop type thrown by Draw it in console.
See screenshot for the error message:
![drawit-warning](https://user-images.githubusercontent.com/18126337/37703336-2aba4930-2d17-11e8-8b18-ca1ae63e2498.png)

**Comment by aw-yt** [comment]
Opened a PR #14  to fix this issue.

**Comment by waleedyt** [comment]
This was fixed by a merge from #15.
